In [2]:
#pip install pandas
#pip install pathlib
#python -m pip install openpyxl

In [3]:
import pandas as pd
from pathlib import Path

In [4]:
pasta_origem = Path("dados/origem")
pasta_bronze = Path("dados/bronze")

In [5]:
arquivo_tab3 = pasta_origem / "projecoes_2024_tab3_grupos_etarios_especificos.xlsx"

df_tab3 = pd.read_excel(arquivo_tab3)
df_tab3.head(12)

,"Projeções das Populações, Revisão 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66,Unnamed: 67,Unnamed: 68
0,"Brasil, Grandes Regiões e Unidades da Federação",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,População por sexo e grupos etários - 2000/2070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,POPULAÇÃO,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,TOTAL,NaN,NaN,CRIANÇAS E JOVENS,NaN,NaN,...,NaN,IDOSOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,ANO,CÓD.,SIGLA,LOCAL,POP_T,POP_H,POP_M,0-1_T,0-1_H,0-1_M,...,P_15-64_M,P_60+_T,P_60+_H,P_60+_M,P_65+_T,P_65+_H,P_65+_M,P_80+_T,P_80+_H,P_80+_M
6,2000,0,BR,Brasil,174695935,85720706,88975229,3423475,1739603,1683872,...,0.326749,0.08718,0.039357,0.047823,0.060261,0.026581,0.03368,0.011633,0.004666,0.006967
7,2001,0,BR,Brasil,177003743,86821427,90182316,3347313,1704785,1642528,...,0.329195,0.088406,0.039845,0.048562,0.06125,0.026957,0.034293,0.011851,0.004749,0.007102
8,2002,0,BR,Brasil,179228254,87882321,91345933,3274356,1671125,1603231,...,0.331573,0.089695,0.040361,0.049334,0.062338,0.027381,0.034957,0.012125,0.004845,0.007279
9,2003,0,BR,Brasil,181377654,88907299,92470355,3212295,1642237,1570058,...,0.333854,0.091074,0.040919,0.050156,0.063486,0.027834,0.035652,0.012443,0.004952,0.007491
10,2004,0,BR,Brasil,183469593,89905311,93564282,3163041,1619035,1544006,...,0.336031,0.092611,0.04155,0.051061,0.064668,0.028304,0.036364,0.012801,0.00507,0.007731
11,2005,0,BR,Brasil,185518369,90883721,94634648,3123546,1599962,1523584,...,0.33813,0.094361,0.042284,0.052077,0.06588,0.02879,0.03709,0.013195,0.0052,0.007995

### Identificação do cabeçalho real

A inspeção mostrou que as primeiras linhas do arquivo são apenas títulos e agrupamentos visuais da planilha. O cabeçalho efetivo dos dados está na linha que contém campos como `ANO`, `CÓD.`, `SIGLA`, `LOCAL`, `POP_T` e os grupos etários.

Na próxima leitura, essa linha será definida como cabeçalho, mantendo os dados originais e tornando a estrutura utilizável pelo Pandas.

In [6]:
df_tab3 = pd.read_excel(arquivo_tab3,header=6)
df_tab3.head()

,ANO,CÓD.,SIGLA,LOCAL,POP_T,POP_H,POP_M,0-1_T,0-1_H,0-1_M,...,P_15-64_M,P_60+_T,P_60+_H,P_60+_M,P_65+_T,P_65+_H,P_65+_M,P_80+_T,P_80+_H,P_80+_M
0,2000,0,BR,Brasil,174695935,85720706,88975229,3423475,1739603,1683872,...,0.326749,0.087180,0.039357,0.047823,0.060261,0.026581,0.033680,0.011633,0.004666,0.006967
1,2001,0,BR,Brasil,177003743,86821427,90182316,3347313,1704785,1642528,...,0.329195,0.088406,0.039845,0.048562,0.061250,0.026957,0.034293,0.011851,0.004749,0.007102
2,2002,0,BR,Brasil,179228254,87882321,91345933,3274356,1671125,1603231,...,0.331573,0.089695,0.040361,0.049334,0.062338,0.027381,0.034957,0.012125,0.004845,0.007279
3,2003,0,BR,Brasil,181377654,88907299,92470355,3212295,1642237,1570058,...,0.333854,0.091074,0.040919,0.050156,0.063486,0.027834,0.035652,0.012443,0.004952,0.007491
4,2004,0,BR,Brasil,183469593,89905311,93564282,3163041,1619035,1544006,...,0.336031,0.092611,0.041550,0.051061,0.064668,0.028304,0.036364,0.012801,0.005070,0.007731

### Inspeção da estrutura dos dados

Com o cabeçalho corretamente identificado, a próxima etapa consiste em verificar as dimensões e os tipos de dados presentes na base.

Essa inspeção permite compreender a estrutura recebida antes de qualquer processo de limpeza ou transformação, preservando as características dos dados na etapa inicial de ingestão.

In [7]:
df_tab3.shape

(2343, 69)

In [8]:
df_tab3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 69 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ANO        2343 non-null   int64
 1   CÓD.       2343 non-null   int64
 2   SIGLA      2343 non-null   object
 3   LOCAL      2343 non-null   object
 4   POP_T      2343 non-null   int64
 5   POP_H      2343 non-null   int64
 6   POP_M      2343 non-null   int64
 7   0-1_T      2343 non-null   int64
 8   0-1_H      2343 non-null   int64
 9   0-1_M      2343 non-null   int64
 10  0-4_T      2343 non-null   int64
 11  0-4_H      2343 non-null   int64
 12  0-4_M      2343 non-null   int64
 13  0-14_T     2343 non-null   int64
 14  0-14_H     2343 non-null   int64
 15  0-14_M     2343 non-null   int64
 16  15-17_T    2343 non-null   int64
 17  15-17_H    2343 non-null   int64
 18  15-17_M    2343 non-null   int64
 19  18-21_T    2343 non-null   int64
 20  18-21_H    2343 non-null   int64
 21  18-21_M    2343 non-null   int64
 22  15-59_T    2343 non-null   int64
 23  15-59_H    2343 non-null   int64
 24  15-59_M    2343 non-null   int64
 25  15-64_T    2343 non-null   int64
 26  15-64_H    2343 non-null   int64
 27  15-64_M    2343 non-null   int64
 28  60+_T      2343 non-null   int64
 29  60+_H      2343 non-null   int64
 30  60+_M      2343 non-null   int64
 31  65+_T      2343 non-null   int64
 32  65+_H      2343 non-null   int64
 33  65+_M      2343 non-null   int64
 34  80+_T      2343 non-null   int64
 35  80+_H      2343 non-null   int64
 36  80+_M      2343 non-null   int64
 37  P_H        2343 non-null   float64
 38  P_M        2343 non-null   float64
 39  P_0-1_T    2343 non-null   float64
 40  P_0-1_H    2343 non-null   float64
 41  P_0-1_M    2343 non-null   float64
 42  P_0-4_T    2343 non-null   float64
 43  P_0-4_H    2343 non-null   float64
 44  P_0-4_M    2343 non-null   float64
 45  P_0-14_T   2343 non-null   float64
 46  P_0-14_H   2343 non-null   float64
 47  P_0-14_M   2343 non-null   float64
 48  P_15-17_T  2343 non-null   float64
 49  P_15-17_H  2343 non-null   float64
 50  P_15-17_M  2343 non-null   float64
 51  P_18-21_T  2343 non-null   float64
 52  P_18-21_H  2343 non-null   float64
 53  P_18-21_M  2343 non-null   float64
 54  P_15-59_T  2343 non-null   float64
 55  P_15-59_H  2343 non-null   float64
 56  P_15-59_M  2343 non-null   float64
 57  P_15-64_T  2343 non-null   float64
 58  P_15-64_H  2343 non-null   float64
 59  P_15-64_M  2343 non-null   float64
 60  P_60+_T    2343 non-null   float64
 61  P_60+_H    2343 non-null   float64
 62  P_60+_M    2343 non-null   float64
 63  P_65+_T    2343 non-null   float64
 64  P_65+_H    2343 non-null   float64
 65  P_65+_M    2343 non-null   float64
 66  P_80+_T    2343 non-null   float64
 67  P_80+_H    2343 non-null   float64
 68  P_80+_M    2343 non-null   float64
dtypes: float64(32), int64(35), object(2)
memory usage: 1.2+ MB

### Resultado da inspeção da base

A base de grupos etários do IBGE possui **2.343 registros e 69 colunas**.

A inspeção inicial mostrou que todas as colunas possuem a mesma quantidade de registros não nulos, não sendo identificados valores ausentes nesta etapa. Os tipos de dados também se apresentam compatíveis com a estrutura esperada, contendo variáveis numéricas e campos textuais de identificação territorial.

Com a estrutura da primeira fonte validada, os dados podem seguir para o processo de ingestão na camada Bronze.

### Consolidação da base na camada Bronze

Após a identificação correta do cabeçalho e a validação da estrutura da base, os dados serão salvos na camada Bronze.

Nesta etapa, não serão aplicadas transformações de negócio, exclusões de colunas ou ajustes nos valores. O objetivo é apenas consolidar a base em um formato estruturado e rastreável para que posteriormente seja tratada na camada Silver.

In [9]:
arquivo_bronze_tab3 = pasta_bronze / "ibge_grupos_etarios_csl.csv"

df_tab3.to_csv(
    arquivo_bronze_tab3,
    index=False,
    encoding="utf-8-sig"
)

print(f"Arquivo salvo em: {arquivo_bronze_tab3}")

Arquivo salvo em: dados\bronze\ibge_grupos_etarios_csl.csv

In [10]:
arquivo_bronze_tab3.exists()

True

### Ingestão da base de indicadores demográficos

Com a primeira base consolidada na camada Bronze, será iniciada a ingestão da base de indicadores demográficos do IBGE.

Assim como na etapa anterior, a estrutura original será inicialmente inspecionada para identificar corretamente o cabeçalho e validar os dados antes de seu armazenamento na camada Bronze.

In [11]:
arquivo_tab4 = pasta_origem / "projecoes_2024_tab4_indicadores.xlsx"

df_tab4 = pd.read_excel(arquivo_tab4)

df_tab4.head(12)

,"Projeções das Populações, Revisão 2024",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58
0,"Brasil, Grandes Regiões e Unidades da Federação",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Indicadores Implícitos - 2000/2070,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,POPULAÇÃO,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,INDICE DE ENVELHECIMENTO,NaN,NaN,ESTATISTICAS DE IDADE,NaN
4,NaN,NaN,NaN,NaN,TOTAL,NaN,NaN,TAXA DE CRESCIMENTO GEOMÉTRICO (%),NaN,NaN,...,IDOSOS\n(60+),TOTAL\n(0-14 e 60+),JOVENS\n(0-14),IDOSOS\n(65+),TOTAL\n(0-14 e 65+),(60+),(65+),(80+),MÉDIA,MEDIANA
5,ANO,CÓD.,SIGLA,LOCAL,POP_T,POP_H,POP_M,TCG_T,TCG_H,TCG_M,...,RDI60,RDT60,RDJ65,RDI65,RDT65,IE60,IE65,IE80,ID_M,ID_MED
6,2000,0,BR,Brasil,174695935,85720706,88975229,NaN,NaN,NaN,...,14.206208,62.953355,46.698707,9.407064,56.105772,29.142644,20.144164,3.888745,28.314517,25.286941
7,2001,0,BR,Brasil,177003743,86821427,90182316,1.321043,1.284078,1.356655,...,14.307632,61.839348,45.530672,9.495381,55.026053,30.101231,20.85491,4.035052,28.572942,25.595223
8,2002,0,BR,Brasil,179228254,87882321,91345933,1.256759,1.221926,1.290294,...,14.419914,60.766364,44.393946,9.599581,53.993527,31.113308,21.623625,4.205821,28.845196,25.923454
9,2003,0,BR,Brasil,181377654,88907299,92470355,1.199253,1.166307,1.230949,...,14.550357,59.763442,43.304364,9.714486,53.01885,32.181739,22.433041,4.396686,29.128255,26.278205
10,2004,0,BR,Brasil,183469593,89905311,93564282,1.153361,1.122531,1.183003,...,14.711434,58.851646,42.26421,9.836084,52.100294,33.328869,23.272845,4.606715,29.420245,26.650273
11,2005,0,BR,Brasil,185518369,90883721,94634648,1.116684,1.088267,1.14399,...,14.911849,58.02942,41.260461,9.962499,51.22296,34.584159,24.14539,4.835904,29.720075,27.035719

### Identificação do cabeçalho da base de indicadores

A inspeção da base de indicadores demográficos mostrou que o arquivo possui a mesma organização inicial encontrada na base de grupos etários, com linhas destinadas a títulos e agrupamentos visuais.

O cabeçalho efetivo está na linha que contém campos como `ANO`, `CÓD.`, `SIGLA`, `LOCAL`, `POP_T`, `TCG_T`, `RDI60`, `IE60` e `ID_MED`.

A base será relida utilizando essa linha como cabeçalho, preservando os dados originais para posterior consolidação na camada Bronze.

In [12]:
df_tab4 = pd.read_excel(
    arquivo_tab4,
    header=6
)

df_tab4.head()

,ANO,CÓD.,SIGLA,LOCAL,POP_T,POP_H,POP_M,TCG_T,TCG_H,TCG_M,...,RDI60,RDT60,RDJ65,RDI65,RDT65,IE60,IE65,IE80,ID_M,ID_MED
0,2000,0,BR,Brasil,174695935,85720706,88975229,NaN,NaN,NaN,...,14.206208,62.953355,46.698707,9.407064,56.105772,29.142644,20.144164,3.888745,28.314517,25.286941
1,2001,0,BR,Brasil,177003743,86821427,90182316,1.321043,1.284078,1.356655,...,14.307632,61.839348,45.530672,9.495381,55.026053,30.101231,20.854910,4.035052,28.572942,25.595223
2,2002,0,BR,Brasil,179228254,87882321,91345933,1.256759,1.221926,1.290294,...,14.419914,60.766364,44.393946,9.599581,53.993527,31.113308,21.623625,4.205821,28.845196,25.923454
3,2003,0,BR,Brasil,181377654,88907299,92470355,1.199253,1.166307,1.230949,...,14.550357,59.763442,43.304364,9.714486,53.018850,32.181739,22.433041,4.396686,29.128255,26.278205
4,2004,0,BR,Brasil,183469593,89905311,93564282,1.153361,1.122531,1.183003,...,14.711434,58.851646,42.264210,9.836084,52.100294,33.328869,23.272845,4.606715,29.420245,26.650273

In [13]:
df_tab4.shape

(2343, 59)

In [14]:
df_tab4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 59 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ANO        2343 non-null   int64
 1   CÓD.       2343 non-null   int64
 2   SIGLA      2343 non-null   object
 3   LOCAL      2343 non-null   object
 4   POP_T      2343 non-null   int64
 5   POP_H      2343 non-null   int64
 6   POP_M      2343 non-null   int64
 7   TCG_T      2310 non-null   float64
 8   TCG_H      2310 non-null   float64
 9   TCG_M      2310 non-null   float64
 10  RS         2343 non-null   float64
 11  NASC_T     2343 non-null   int64
 12  NASC_H     2343 non-null   int64
 13  NASC_M     2343 non-null   int64
 14  OBT_T      2343 non-null   int64
 15  OBT_H      2343 non-null   int64
 16  OBT_M      2343 non-null   int64
 17  TBN        2343 non-null   float64
 18  TBM        2343 non-null   float64
 19  TCV        2343 non-null   float64
 20  e0_T       2343 non-null   float64
 21  e0_H       2343 non-null   float64
 22  e0_M       2343 non-null   float64
 23  e60_T      2343 non-null   float64
 24  e60_H      2343 non-null   float64
 25  e60_M      2343 non-null   float64
 26  TMI_T      2343 non-null   float64
 27  TMI_H      2343 non-null   float64
 28  TMI_M      2343 non-null   float64
 29  5q0_T      2343 non-null   float64
 30  5q0_H      2343 non-null   float64
 31  5q0_M      2343 non-null   float64
 32  45q15_T    2343 non-null   float64
 33  45q15_H    2343 non-null   float64
 34  45q15_M    2343 non-null   float64
 35  20q60_T    2343 non-null   float64
 36  20q60_H    2343 non-null   float64
 37  20q60_M    2343 non-null   float64
 38  TFT        2343 non-null   float64
 39  TEF_10-14  2343 non-null   float64
 40  TEF_15-19  2343 non-null   float64
 41  TEF_20-24  2343 non-null   float64
 42  TEF_25-29  2343 non-null   float64
 43  TEF_30-34  2343 non-null   float64
 44  TEF_35-39  2343 non-null   float64
 45  TEF_40-44  2343 non-null   float64
 46  TEF_45-49  2343 non-null   float64
 47  TEF_50+    2343 non-null   float64
 48  RDJ60      2343 non-null   float64
 49  RDI60      2343 non-null   float64
 50  RDT60      2343 non-null   float64
 51  RDJ65      2343 non-null   float64
 52  RDI65      2343 non-null   float64
 53  RDT65      2343 non-null   float64
 54  IE60       2343 non-null   float64
 55  IE65       2343 non-null   float64
 56  IE80       2343 non-null   float64
 57  ID_M       2343 non-null   float64
 58  ID_MED     2343 non-null   float64
dtypes: float64(46), int64(11), object(2)
memory usage: 1.1+ MB

### Resultado da inspeção da base de indicadores

A base de indicadores demográficos do IBGE possui **2.343 registros e 59 colunas**.

A inspeção identificou que a maior parte das variáveis está completamente preenchida. As colunas referentes à Taxa de Crescimento Geométrico (`TCG_T`, `TCG_H` e `TCG_M`) apresentam 33 valores ausentes, característica que será preservada nesta etapa por fazer parte da estrutura original dos dados.

Com a estrutura validada, a segunda base do IBGE está pronta para ser consolidada na camada Bronze.

In [15]:
arquivo_bronze_tab4 = pasta_bronze / "ibge_indicadores_csl.csv"

df_tab4.to_csv(
    arquivo_bronze_tab4,
    index=False,
    encoding="utf-8-sig"
)

print(f"Arquivo salvo em: {arquivo_bronze_tab4}")

Arquivo salvo em: dados\bronze\ibge_indicadores_csl.csv

In [16]:
arquivo_bronze_tab4.exists()

True

### Ingestão da base de contribuintes da Previdência Social

A última fonte utilizada na camada Bronze corresponde aos dados de contribuintes da Previdência Social, disponibilizados pelo Anuário Estatístico da Previdência Social (AEPS).

Inicialmente, a planilha será carregada sem tratamentos para identificar sua estrutura, localizar corretamente o cabeçalho e verificar a organização dos dados antes de sua consolidação na camada Bronze.

In [17]:
arquivo_aeps = pasta_origem / "Número_Contribuintes_2022_2024_24C32_03.xlsx"

df_aeps = pd.read_excel(arquivo_aeps)

df_aeps.head(15)

,Capítulo 32 - Contribuintes pessoas físicas,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,32.3 - Número médio mensal de contribuintes pe...,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,/ ANOS,NaN,NÚMERO MÉDIO MENSAL DE CONTRIBUINTES PESSOAS F...,NaN,NaN,NaN
3,NaN,NaN,Total,Sexo,NaN,NaN
4,NaN,NaN,NaN,Masculino,Feminino,Ignorado
5,TOTAL,2022.0,58272885,31236748,26960253,75884
6,NaN,2023.0,60532508,32397067,28112041,23400
7,NaN,2024.0,62180770,33230738,28926291,23740
8,Até 19 anos,2022.0,1279843,683859,589057,6927
9,NaN,2023.0,1379548,735533,643945,70
10,NaN,2024.0,1530144,809522,720578,43
11,20 a 24 anos,2022.0,5884867,3223538,2653205,8124
12,NaN,2023.0,6026451,3298627,2727517,307
13,NaN,2024.0,6127670,3343110,2784337,223
14,25 a 29 anos,2022.0,7712262,4147165,3559290,5808

### Inspeção da estrutura da base de contribuintes

A inspeção da planilha do AEPS identificou uma estrutura diferente das bases do IBGE. O arquivo apresenta cabeçalho distribuído em múltiplas linhas e organiza os registros por faixa etária e ano.

Também foi observado que a identificação da faixa etária aparece apenas no primeiro registro de cada grupo, permanecendo vazia nas linhas subsequentes referentes aos demais anos.

Essas características serão preservadas na camada Bronze, deixando os processos de padronização e preenchimento para a etapa de tratamento na camada Silver.

In [18]:
df_aeps.tail(15)

,Capítulo 32 - Contribuintes pessoas físicas,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
38,65 a 69 anos,2022.0,872981,509756,362935,290
39,NaN,2023.0,950282,559611,390524,148
40,NaN,2024.0,1018073,604347,413579,147
41,70 anos e mais,2022.0,446531,272443,173930,157
42,NaN,2023.0,494466,302185,192133,148
43,NaN,2024.0,543779,333300,210317,162
44,Ignorada,2022.0,19905,9,7,19889
45,NaN,2023.0,13621,243,144,13235
46,NaN,2024.0,14953,239,141,14573
47,NaN,NaN,NaN,NaN,NaN,NaN
48,"FONTE: DATAPREV, CNIS, Tabulação Especial GFIP...",NaN,NaN,NaN,NaN,NaN
49,NOTAS: 1. O número médio mensal de contribuint...,NaN,NaN,NaN,NaN,NaN
50,2. As diferenças porventura existentes entre a...,NaN,NaN,NaN,NaN,NaN
51,"3. Os dados de 2024 são preliminares, e serão ...",NaN,NaN,NaN,NaN,NaN
52,"A partir de outubro de 2022, os órgãos público...",NaN,NaN,NaN,NaN,NaN

### Delimitação dos registros da base de contribuintes

A inspeção final da planilha do AEPS mostrou que, além dos registros de contribuintes, o arquivo possui ao final uma linha em branco, a identificação da fonte e notas metodológicas.

Os registros da tabela estão separados dessas informações complementares. Para a consolidação na camada Bronze será preservado o conteúdo tabular destinado ao processamento, enquanto o arquivo original permanecerá armazenado integralmente na pasta de origem, garantindo a rastreabilidade das informações e das notas fornecidas pela fonte.

In [19]:
df_aeps_bronze = pd.read_excel(
    arquivo_aeps,
    header=None,
    skiprows=1,
    nrows=47
)

df_aeps_bronze.head(10)

,0,1,2,3,4,5
0,32.3 - Número médio mensal de contribuintes pe...,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,/ ANOS,NaN,NÚMERO MÉDIO MENSAL DE CONTRIBUINTES PESSOAS F...,NaN,NaN,NaN
3,NaN,NaN,Total,Sexo,NaN,NaN
4,NaN,NaN,NaN,Masculino,Feminino,Ignorado
5,TOTAL,2022.0,58272885,31236748,26960253,75884
6,NaN,2023.0,60532508,32397067,28112041,23400
7,NaN,2024.0,62180770,33230738,28926291,23740
8,Até 19 anos,2022.0,1279843,683859,589057,6927
9,NaN,2023.0,1379548,735533,643945,70

### Consolidação da base de contribuintes na camada Bronze

Após a inspeção da estrutura da planilha, foi delimitado o bloco correspondente à tabela de contribuintes da Previdência Social.

Os dados serão armazenados mantendo sua estrutura original, incluindo o cabeçalho em múltiplas linhas e os valores ausentes existentes na fonte. As etapas de limpeza, padronização e reorganização serão realizadas posteriormente na camada Silver.

In [20]:
arquivo_bronze_aeps = pasta_bronze / "aeps_contribuintes_csl.csv"

df_aeps_bronze.to_csv(
    arquivo_bronze_aeps,
    index=False,
    header=False,
    encoding="utf-8-sig"
)

print(f"Arquivo salvo em: {arquivo_bronze_aeps}")

Arquivo salvo em: dados\bronze\aeps_contribuintes_csl.csv

In [21]:
arquivo_bronze_aeps.exists()

True

### Validação final da camada Bronze

Com as três fontes consolidadas, será realizada uma verificação final dos arquivos gerados na camada Bronze.

O objetivo é confirmar que todas as bases previstas foram armazenadas corretamente antes do início da etapa de tratamento dos dados na camada Silver.

In [22]:
arquivos_bronze = list(pasta_bronze.glob("*.csv"))

for arquivo in arquivos_bronze:
    print(arquivo.name)

aeps_contribuintes_csl.csv
ibge_grupos_etarios_csl.csv
ibge_indicadores_csl.csv

### Verificação dos arquivos consolidados

Após confirmar a existência dos três arquivos da camada Bronze, será realizada uma leitura de validação dos dados consolidados.

Essa verificação garante que os arquivos gerados podem ser acessados novamente pelo pipeline e que estão disponíveis para utilização na próxima etapa da Arquitetura Medalhão.

In [23]:
teste_tab3 = pd.read_csv(pasta_bronze / "ibge_grupos_etarios_csl.csv")
teste_tab4 = pd.read_csv(pasta_bronze / "ibge_indicadores_csl.csv")
teste_aeps = pd.read_csv(pasta_bronze / "aeps_contribuintes_csl.csv", header=None)

print("IBGE - Grupos etários:", teste_tab3.shape)
print("IBGE - Indicadores:", teste_tab4.shape)
print("AEPS - Contribuintes:", teste_aeps.shape)

IBGE - Grupos etários: (2343, 69)
IBGE - Indicadores: (2343, 59)
AEPS - Contribuintes: (47, 6)

## AEPS — Série histórica de contribuintes

Com o objetivo de ampliar o horizonte temporal da análise previdenciária, foi incorporada ao projeto a série histórica do Anuário Estatístico da Previdência Social (AEPS).

A base apresenta a quantidade de contribuintes pessoas físicas no período de 2003 a 2023, permitindo complementar os dados detalhados de contribuintes já disponíveis para 2022, 2023 e 2024.

Nesta etapa da camada Bronze, o arquivo será apenas ingerido e preservado em sua estrutura original. Os tratamentos necessários serão realizados posteriormente na camada Silver.

In [24]:
arquivo_aeps_historico_contrib = pasta_origem / "23SH5_01.xlsx"

df_aeps_historico_contrib = pd.read_excel(
    arquivo_aeps_historico_contrib,
    header=None
)

df_aeps_historico_contrib.head(15)

,0,1,2,3,4,5,6,7,8,9,10
0,Capítulo 5 - Contribuintes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5.1 - Quantidade de contribuintes pessoas físi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ANOS,QUANTIDADE DE CONTRIBUINTES PESSOAS FÍSICAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Total,Trabalhadores\nEmpregados (I),Outros Contribuintes (1),NaN,NaN,NaN,Ambos,NaN,NaN,NaN
5,NaN,NaN,NaN,Total,GPS (II),GFIP (III),GPS e GFIP\n(IV),Total,(I) e (II)\nconjuntamente,(I) e (III)\nconjuntamente,(I) e (IV)\nconjuntamente
6,2003,39850452,30537383,8395885,4704900,2120751,1570234,917184,254569,580788,81827
7,2004,42084323,32200411,8766902,4592168,3850082,324652,1117010,256764,835901,24345
8,2005,45035035,34687001,9099704,4693028,4114667,292009,1248330,280717,943844,23769
9,2006,46676737,36158570,9262079,4725699,4275536,260844,1256088,277327,958280,20481
10,2007,49936338,38788600,9710280,4966598,4484207,259475,1437458,264257,1150856,22345
11,2008,53964928,42076251,10235457,5274811,4699830,260816,1653220,323299,1304610,25311
12,2009,55877835,43439321,10684737,5635715,4785919,263103,1753777,359217,1368463,26097
13,2010,60197924,46683012,11548708,6360555,4911110,277043,1966204,460542,1474535,31127
14,2011,64292255,49690560,12441787,7182932,4975675,283180,2159908,569239,1555705,34964

In [25]:
arquivo_bronze_aeps_historico_contrib = (
    pasta_bronze / "aeps_historico_contribuintes.csv"
)

df_aeps_historico_contrib.to_csv(
    arquivo_bronze_aeps_historico_contrib,
    index=False,
    header=False,
    encoding="utf-8-sig"
)

print(
    f"Arquivo salvo em: {arquivo_bronze_aeps_historico_contrib}"
)

Arquivo salvo em: dados\bronze\aeps_historico_contribuintes.csv

In [26]:
arquivo_bronze_aeps_historico_contrib.exists()

True

## AEPS — Série histórica de benefícios

Para complementar a análise previdenciária, também foi incorporada a série histórica de benefícios emitidos do Anuário Estatístico da Previdência Social (AEPS).

A base apresenta a quantidade de benefícios emitidos segundo os grupos de espécies no período de 2005 a 2023, incluindo os benefícios previdenciários e suas diferentes categorias, como aposentadorias.

Essa série permitirá, nas etapas posteriores do projeto, comparar a evolução histórica dos contribuintes com a evolução dos benefícios emitidos.

Nesta etapa da camada Bronze, o arquivo será apenas ingerido e preservado em sua estrutura original. Os tratamentos e a seleção das variáveis relevantes serão realizados posteriormente na camada Silver.

In [27]:
arquivo_aeps_historico_benef = pasta_origem / "23SH1_10.xlsx"

df_aeps_historico_benef = pd.read_excel(
    arquivo_aeps_historico_benef,
    header=None
)

df_aeps_historico_benef.head(15)

,0,1,2,3,4,5,6,7,8,9,10
0,Capítulo 1 - Benefícios,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"1.10 - Quantidade de beneficios emitidos, segu...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(continua),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,GRUPOS DE ESPÉCIES,QUANTIDADE DE BENEFÍCIOS EMITIDOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014
6,TOTAL,23951320,24593390,25170283,26095625,27048356,28141263,29051423,30057265,31199043,32152518
7,BENEFÍCIOS DO RGPS,21158137,21644885,22066263,22776205,23534497,24426882,25176323,26032855,27009011,27818973
8,Previdenciários,20402333,20912090,21297610,21972664,22736409,23598754,24341783,25192966,26150959,26957844
9,Aposentadorias,13053959,13446661,13878747,14453455,15076295,15606264,16139303,16725927,17351730,17940405
10,Tempo de Contribuição,3703364,3791655,3943339,4117972,4316779,4486698,4672643,4862215,5064342,5254911
11,Idade,6676958,6915487,7182325,7500092,7856916,8161733,8457025,8798101,9165014,9508695
12,Invalidez,2673637,2739519,2753083,2835391,2902600,2957833,3009635,3065611,3122374,3176799
13,Pensão por Morte,5783244,5920592,6090410,6274676,6457846,6631064,6797204,6976263,7159242,7316534
14,Auxílios,1522003,1501906,1282412,1188984,1130431,1288126,1330811,1407703,1548284,1614821

In [28]:
arquivo_bronze_aeps_historico_benef = (
    pasta_bronze / "aeps_historico_beneficios.csv"
)

df_aeps_historico_benef.to_csv(
    arquivo_bronze_aeps_historico_benef,
    index=False,
    header=False,
    encoding="utf-8-sig"
)

print(
    f"Arquivo salvo em: {arquivo_bronze_aeps_historico_benef}"
)

Arquivo salvo em: dados\bronze\aeps_historico_beneficios.csv

In [29]:
arquivo_bronze_aeps_historico_benef.exists()

True

# Conclusão da camada Bronze

A camada Bronze foi concluída com a ingestão e preservação das cinco bases de dados utilizadas no projeto:

- **IBGE — Grupos etários:** 2.343 registros e 69 colunas;
- **IBGE — Indicadores demográficos:** 2.343 registros e 59 colunas;
- **AEPS — Contribuintes da Previdência Social (2022–2024):** estrutura original consolidada em 47 linhas e 6 colunas;
- **AEPS — Série histórica de contribuintes (2003–2023):** série histórica incorporada para ampliar o horizonte temporal da análise previdenciária;
- **AEPS — Série histórica de benefícios (2005–2023):** série histórica de benefícios emitidos, incluindo as categorias previdenciárias e aposentadorias.

Os arquivos de origem foram preservados separadamente e as cinco bases foram armazenadas na camada Bronze antes da aplicação de tratamentos e transformações.

A incorporação das séries históricas do AEPS amplia o horizonte temporal do projeto e permite que, nas próximas etapas, a evolução dos contribuintes e dos benefícios seja analisada em conjunto com a evolução demográfica brasileira.

A partir deste ponto, o projeto seguirá para a **camada Silver**, responsável pela limpeza, padronização e preparação das novas séries históricas para posterior integração e análise.