# Camada Gold

A camada Gold representa a etapa analítica da Arquitetura Medalhão.

Nesta fase, serão utilizadas as bases tratadas e validadas na camada Silver para integrar informações demográficas do IBGE com dados de contribuintes da Previdência Social.

O objetivo é construir conjuntos de dados voltados às análises do projeto, permitindo observar a evolução da estrutura etária da população, indicadores de envelhecimento e a relação entre população e contribuintes previdenciários.

As transformações realizadas nesta etapa serão orientadas pelas perguntas e indicadores que se pretende analisar, preservando as bases da camada Silver como fonte dos dados tratados.

In [2]:
import pandas as pd
from pathlib import Path

pasta_silver = Path("dados/silver")
pasta_gold = Path("dados/gold")

## Leitura das bases tratadas da camada Silver

Com as seis bases tratadas e validadas na camada Silver, inicia-se a construção da camada Gold.

Nesta etapa, serão carregadas as bases demográficas do IBGE e as bases previdenciárias do AEPS que servirão de origem para a construção dos conjuntos analíticos.

As bases possuem diferentes períodos e níveis de detalhamento. Por esse motivo, elas serão inicialmente mantidas separadas e integradas posteriormente de acordo com os objetivos de cada análise.

In [3]:
df_grupos_etarios = pd.read_csv(
    pasta_silver / "ibge_grupos_etarios_tratado.csv"
)

df_indicadores = pd.read_csv(
    pasta_silver / "ibge_indicadores_tratado.csv"
)

df_contribuintes_idade = pd.read_csv(
    pasta_silver / "aeps_contribuintes_tratado.csv"
)

df_historico_contribuintes = pd.read_csv(
    pasta_silver / "aeps_historico_contribuintes_tratado.csv"
)

df_historico_beneficios = pd.read_csv(
    pasta_silver / "aeps_historico_beneficios_tratado.csv"
)

df_media_mensal = pd.read_csv(
    pasta_silver / "aeps_media_mensal_contribuintes_tratado.csv"
)

In [4]:
print("IBGE - Grupos etários:", df_grupos_etarios.shape)
print("IBGE - Indicadores:", df_indicadores.shape)
print("AEPS - Contribuintes por idade:", df_contribuintes_idade.shape)
print("AEPS - Histórico de contribuintes:", df_historico_contribuintes.shape)
print("AEPS - Histórico de benefícios:", df_historico_beneficios.shape)
print("RGPS - Média mensal de contribuintes:", df_media_mensal.shape)

IBGE - Grupos etários: (2343, 15)
IBGE - Indicadores: (2343, 15)
AEPS - Contribuintes por idade: (42, 6)
AEPS - Histórico de contribuintes: (21, 5)
AEPS - Histórico de benefícios: (19, 5)
RGPS - Média mensal de contribuintes: (19, 3)

## Construção da base demográfica analítica

As duas bases do IBGE apresentam informações complementares sobre a evolução demográfica brasileira.

A base de grupos etários contém a distribuição da população por grandes grupos de idade, enquanto a base de indicadores reúne medidas como fecundidade, expectativa de vida, razão de dependência e índice de envelhecimento.

Como ambas abrangem o período de 2000 a 2070 e possuem informações para as mesmas localidades, será inicialmente verificada a compatibilidade das chaves utilizadas para identificar cada observação antes da integração das duas bases.

In [5]:
print("Chaves duplicadas - Grupos etários:")
print(
    df_grupos_etarios.duplicated(
        subset=["ano", "codigo", "sigla", "local"]
    ).sum()
)

print("\nChaves duplicadas - Indicadores:")
print(
    df_indicadores.duplicated(
        subset=["ano", "codigo", "sigla", "local"]
    ).sum()
)

Chaves duplicadas - Grupos etários:
0

Chaves duplicadas - Indicadores:
0

## Verificação da correspondência entre as bases demográficas

Após confirmar a unicidade das chaves nas duas bases do IBGE, será verificado se os registros de ano e localidade correspondem integralmente entre as tabelas.

Essa etapa garante que a integração seja realizada apenas após confirmar que cada observação da base de grupos etários possui uma observação correspondente na base de indicadores demográficos.

In [6]:
chaves_demograficas = [
    "ano",
    "codigo",
    "sigla",
    "local"
]

verificacao_chaves = df_grupos_etarios[
    chaves_demograficas
].merge(
    df_indicadores[chaves_demograficas],
    on=chaves_demograficas,
    how="outer",
    indicator=True
)

verificacao_chaves["_merge"].value_counts()

_merge
both          2343
left_only        0
right_only       0
Name: count, dtype: int64

## Integração das bases demográficas

A verificação confirmou que as 2.343 combinações de ano e localidade possuem correspondência integral entre as duas bases do IBGE.

Com essa compatibilidade confirmada, as informações de grupos etários e indicadores demográficos serão integradas em uma única base analítica.

Como a variável `populacao_total` está presente nas duas fontes, será mantida apenas uma ocorrência dessa informação, evitando duplicidade de variáveis na base resultante.

In [7]:
colunas_indicadores = [
    coluna for coluna in df_indicadores.columns
    if coluna not in chaves_demograficas + ["populacao_total"]
]

df_demografia_gold = df_grupos_etarios.merge(
    df_indicadores[
        chaves_demograficas + colunas_indicadores
    ],
    on=chaves_demograficas,
    how="inner",
    validate="one_to_one"
)

df_demografia_gold.shape

(2343, 25)

## Verificação da estrutura da base demográfica integrada

Após a integração das duas bases do IBGE, será verificada a estrutura do conjunto analítico resultante.

Essa etapa permite confirmar as variáveis disponíveis na base Gold e verificar se as informações de grupos etários e indicadores demográficos foram incorporadas corretamente antes da criação de novos indicadores e do armazenamento da base.

In [8]:
df_demografia_gold.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2343 entries, 0 to 2342
Data columns (total 25 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ano                       2343 non-null   int64
 1   codigo                    2343 non-null   int64
 2   sigla                     2343 non-null   object
 3   local                     2343 non-null   object
 4   populacao_total           2343 non-null   int64
 5   populacao_0_14            2343 non-null   int64
 6   populacao_15_64           2343 non-null   int64
 7   populacao_60_mais         2343 non-null   int64
 8   populacao_65_mais         2343 non-null   int64
 9   populacao_80_mais         2343 non-null   int64
 10  proporcao_0_14            2343 non-null   float64
 11  proporcao_15_64           2343 non-null   float64
 12  proporcao_60_mais         2343 non-null   float64
 13  proporcao_65_mais         2343 non-null   float64
 14  proporcao_80_mais         2343 non-null   float64
 15  taxa_crescimento          2310 non-null   float64
 16  expectativa_vida          2343 non-null   float64
 17  expectativa_vida_60       2343 non-null   float64
 18  taxa_fecundidade          2343 non-null   float64
 19  razao_dependencia_jovens  2343 non-null   float64
 20  razao_dependencia_idosos  2343 non-null   float64
 21  razao_dependencia_total   2343 non-null   float64
 22  indice_envelhecimento     2343 non-null   float64
 23  idade_media               2343 non-null   float64
 24  idade_mediana             2343 non-null   float64
dtypes: float64(15), int64(8), object(2)
memory usage: 457.7+ KB

## Validação da população total entre as fontes

A variável `populacao_total` está presente nas duas bases demográficas do IBGE. Durante a integração, foi mantida apenas a variável proveniente da base de grupos etários para evitar duplicidade de informações.

Antes de prosseguir com a construção dos indicadores analíticos, será verificado se os valores de população total são equivalentes nas duas fontes para todas as combinações de ano e localidade.

In [9]:
validacao_populacao = df_grupos_etarios[
    chaves_demograficas + ["populacao_total"]
].merge(
    df_indicadores[
        chaves_demograficas + ["populacao_total"]
    ],
    on=chaves_demograficas,
    how="inner",
    suffixes=("_grupos", "_indicadores"),
    validate="one_to_one"
)

diferencas_populacao = (
    validacao_populacao["populacao_total_grupos"]
    != validacao_populacao["populacao_total_indicadores"]
).sum()

print(
    "Registros com diferença na população total:",
    diferencas_populacao
)

Registros com diferença na população total: 0

## Seleção da série demográfica do Brasil

A base demográfica integrada contém informações para o Brasil, regiões e Unidades da Federação. Entretanto, as séries históricas de contribuintes e benefícios do AEPS utilizadas no projeto apresentam abrangência nacional.

Para possibilitar posteriormente a análise conjunta das informações demográficas e previdenciárias, será criada uma série específica para o Brasil.

A base demográfica completa será preservada na camada Gold para análises territoriais, enquanto a série nacional será utilizada como referência para a integração com os dados históricos do AEPS.

In [10]:
df_demografia_brasil = (
    df_demografia_gold[
        df_demografia_gold["local"] == "Brasil"
    ]
    .copy()
    .reset_index(drop=True)
)

print("Dimensão:", df_demografia_brasil.shape)
print(
    "Período:",
    df_demografia_brasil["ano"].min(),
    "a",
    df_demografia_brasil["ano"].max()
)

df_demografia_brasil.head()

Dimensão: (71, 25)
Período: 2000 a 2070

,ano,codigo,sigla,local,populacao_total,populacao_0_14,populacao_15_64,populacao_60_mais,populacao_65_mais,populacao_80_mais,...,taxa_crescimento,expectativa_vida,expectativa_vida_60,taxa_fecundidade,razao_dependencia_jovens,razao_dependencia_idosos,razao_dependencia_total,indice_envelhecimento,idade_media,idade_mediana
0,2000,0,BR,Brasil,174695935,52259915,111908697,15229921,10527323,2032255,...,NaN,71.102185,20.109002,2.315552,48.747147,14.206208,62.953355,29.142644,28.314517,25.286941
1,2001,0,BR,Brasil,177003743,51985452,114176772,15648261,10841519,2097640,...,1.321043,71.502797,20.255832,2.149242,47.531716,14.307632,61.839348,30.101231,28.572942,25.595223
2,2002,0,BR,Brasil,179228254,51668727,116386875,16075850,11172652,2173094,...,1.256759,71.824406,20.361073,2.066614,46.346450,14.419914,60.766364,31.113308,28.845196,25.923454
3,2003,0,BR,Brasil,181377654,51329911,118532883,16518858,11514860,2256815,...,1.199253,72.103568,20.440327,2.016345,45.213085,14.550357,59.763442,32.181739,29.128255,26.278205
4,2004,0,BR,Brasil,183469593,50980818,120624088,16991330,11864687,2348541,...,1.153361,72.587444,20.629628,1.969960,44.140213,14.711434,58.851646,33.328869,29.420245,26.650273

## Verificação da compatibilidade temporal das séries principais

A análise utiliza duas séries principais com abrangência nacional: a série demográfica do IBGE e a série do número médio mensal de contribuintes do RGPS.

A série demográfica abrange o período de 2000 a 2070, enquanto a série do número médio mensal de contribuintes compreende os anos de 2005 a 2023.

A identificação desses períodos permite separar a análise histórica conjunta, limitada aos anos em que ambas as séries possuem dados disponíveis, da análise das projeções demográficas posteriores a 2023.

In [11]:
print(
    "Demografia:",
    df_demografia_brasil["ano"].min(),
    "a",
    df_demografia_brasil["ano"].max()
)

print(
    "Média mensal de contribuintes:",
    df_media_mensal["ano"].min(),
    "a",
    df_media_mensal["ano"].max()
)

inicio_periodo_historico = max(
    df_demografia_brasil["ano"].min(),
    df_media_mensal["ano"].min()
)

fim_periodo_historico = min(
    df_demografia_brasil["ano"].max(),
    df_media_mensal["ano"].max()
)

print(
    "\nPeríodo histórico comum:",
    inicio_periodo_historico,
    "a",
    fim_periodo_historico
)

Demografia: 2000 a 2070
Média mensal de contribuintes: 2005 a 2023

Período histórico comum: 2005 a 2023

## Construção da base histórica integrada

Para analisar conjuntamente as transformações demográficas e previdenciárias ocorridas no período histórico, serão integradas as informações nacionais do IBGE com a série do número médio mensal de contribuintes e a série histórica de benefícios do RGPS.

A integração considera o período comum de 2005 a 2023 e reúne as principais variáveis necessárias para comparar a evolução da população em idade potencialmente ativa, da população idosa, da base contributiva e dos benefícios e aposentadorias emitidos.

In [12]:
df_historico_gold = (
    df_demografia_brasil[
        [
            "ano",
            "populacao_total",
            "populacao_15_64",
            "populacao_60_mais"
        ]
    ]
    .merge(
        df_media_mensal[
            [
                "ano",
                "media_mensal_contribuintes"
            ]
        ],
        on="ano",
        how="inner",
        validate="one_to_one"
    )
    .merge(
        df_historico_beneficios[
            [
                "ano",
                "total_beneficios",
                "aposentadorias"
            ]
        ],
        on="ano",
        how="inner",
        validate="one_to_one"
    )
)

df_historico_gold

,ano,populacao_total,populacao_15_64,populacao_60_mais,media_mensal_contribuintes,total_beneficios,aposentadorias
0,2005,185518369,122678705,17505740,32486813,23951320,13053959
1,2006,187535030,124716555,18066993,33333012,24593390,13446661
2,2007,189458827,126742367,18671742,36428202,25170283,13878747
3,2008,191335196,128741904,19316301,39605694,26095625,14453455
4,2009,193174036,130694593,19999039,41045142,27048356,15076295
5,2010,194749329,132415855,20718042,44406673,28141263,15606264
6,2011,196158610,133940245,21475117,47725149,29051423,16139303
7,2012,197670620,135492473,22273483,50907423,30057265,16725927
8,2013,199226702,137041821,23115563,52688194,31199043,17351730
9,2014,200811131,138534751,23998696,54226609,32152518,17940405
10,2015,202403642,139904894,24917618,53604092,32701562,18404135
11,2016,203871925,141113877,25871388,51844313,33755917,19062228
12,2017,205211557,142157814,26861890,51026116,34497835,19807974
13,2018,206529038,143049781,27889518,51633476,35058564,20425962
14,2019,207900099,143936438,28950761,52923137,35636157,21050364
15,2020,209164889,144790679,29979443,51520066,36014002,21408965
16,2021,210103642,145458036,30903117,55134180,36356543,21613852
17,2022,210862983,145928636,31864499,58272885,37623943,22210078
18,2023,211695158,146375852,32981491,60532508,39302525,22826720

In [13]:
print("Dimensão:", df_historico_gold.shape)

print(
    "Período:",
    df_historico_gold["ano"].min(),
    "a",
    df_historico_gold["ano"].max()
)

print("\nValores ausentes:")
print(df_historico_gold.isnull().sum())

print("\nAnos duplicados:")
print(df_historico_gold["ano"].duplicated().sum())

Dimensão: (19, 7)
Período: 2005 a 2023

Valores ausentes:
ano                           0
populacao_total               0
populacao_15_64               0
populacao_60_mais             0
media_mensal_contribuintes    0
total_beneficios              0
aposentadorias                0
dtype: int64

Anos duplicados:
0

## Evolução dos principais componentes no período histórico

Com a base histórica validada, serão comparados os valores observados em 2005 e 2023 para identificar a evolução da população em idade potencialmente ativa, da população idosa, da média mensal de contribuintes, dos benefícios emitidos e das aposentadorias emitidas.

In [15]:
colunas_analise = [
    "populacao_total",
    "populacao_15_64",
    "populacao_60_mais",
    "media_mensal_contribuintes",
    "total_beneficios",
    "aposentadorias"
]

inicio = df_historico_gold.loc[
    df_historico_gold["ano"] == 2005,
    colunas_analise
].iloc[0]

fim = df_historico_gold.loc[
    df_historico_gold["ano"] == 2023,
    colunas_analise
].iloc[0]

df_evolucao_historica = pd.DataFrame({
    "2005": inicio,
    "2023": fim
})

df_evolucao_historica["variacao_percentual"] = (
    (df_evolucao_historica["2023"] / df_evolucao_historica["2005"] - 1) * 100
)

df_evolucao_historica.round(2)

                                 2005       2023  variacao_percentual
populacao_total             185518369  211695158                14.11
populacao_15_64             122678705  146375852                19.32
populacao_60_mais            17505740   32981491                88.40
media_mensal_contribuintes   32486813   60532508                86.33
total_beneficios             23951320   39302525                64.09
aposentadorias               13053959   22826720                74.86

## Análise da trajetória histórica

A comparação entre 2005 e 2023 mostra diferenças importantes no crescimento das variáveis demográficas e previdenciárias. Para identificar em quais momentos essas mudanças ocorreram, será analisada a variação percentual anual de cada série ao longo do período.

In [18]:
df_trajetoria_historica = df_historico_gold.copy()

colunas_trajetoria = [
    "populacao_total",
    "populacao_15_64",
    "populacao_60_mais",
    "media_mensal_contribuintes",
    "total_beneficios",
    "aposentadorias"
]

for coluna in colunas_trajetoria:
    df_trajetoria_historica[f"var_{coluna}"] = (
        df_trajetoria_historica[coluna].pct_change() * 100
    )

colunas_exibicao = [
    "ano",
    "var_populacao_total",
    "var_populacao_15_64",
    "var_populacao_60_mais",
    "var_media_mensal_contribuintes",
    "var_total_beneficios",
    "var_aposentadorias"
]

df_trajetoria_historica[colunas_exibicao].round(2)

,ano,var_populacao_total,var_populacao_15_64,var_populacao_60_mais,var_media_mensal_contribuintes,var_total_beneficios,var_aposentadorias
0,2005,NaN,NaN,NaN,NaN,NaN,NaN
1,2006,1.09,1.66,3.21,2.60,2.68,3.01
2,2007,1.03,1.62,3.35,9.29,2.35,3.21
3,2008,0.99,1.58,3.45,8.72,3.68,4.14
4,2009,0.96,1.52,3.53,3.63,3.65,4.31
5,2010,0.82,1.32,3.60,8.19,4.04,3.52
6,2011,0.72,1.15,3.65,7.47,3.23,3.42
7,2012,0.77,1.16,3.72,6.67,3.46,3.63
8,2013,0.79,1.14,3.78,3.50,3.80,3.74
9,2014,0.80,1.09,3.82,2.92,3.06,3.39
10,2015,0.79,0.99,3.83,-1.15,1.71,2.58
11,2016,0.73,0.86,3.83,-3.28,3.22,3.58
12,2017,0.66,0.74,3.83,-1.58,2.20,3.91
13,2018,0.64,0.63,3.83,1.19,1.63,3.12
14,2019,0.66,0.62,3.81,2.50,1.65,3.06
15,2020,0.61,0.59,3.55,-2.65,1.06,1.70
16,2021,0.45,0.46,3.08,7.01,0.95,0.96
17,2022,0.36,0.32,3.11,5.69,3.49,2.76
18,2023,0.39,0.31,3.51,3.88,4.46,2.78

## Relação entre contribuintes e benefícios no período histórico

Para avaliar a evolução conjunta da base contributiva e do estoque de benefícios, serão calculadas as relações entre o número médio mensal de contribuintes e a quantidade de benefícios e aposentadorias emitidos.

Essas relações são utilizadas como indicadores descritivos da evolução das séries e não representam, de forma literal, a quantidade de trabalhadores que financia cada aposentado.

In [19]:
df_relacoes_previdenciarias = df_historico_gold[
    [
        "ano",
        "media_mensal_contribuintes",
        "total_beneficios",
        "aposentadorias"
    ]
].copy()

df_relacoes_previdenciarias["contribuintes_por_beneficio"] = (
    df_relacoes_previdenciarias["media_mensal_contribuintes"]
    / df_relacoes_previdenciarias["total_beneficios"]
)

df_relacoes_previdenciarias["contribuintes_por_aposentadoria"] = (
    df_relacoes_previdenciarias["media_mensal_contribuintes"]
    / df_relacoes_previdenciarias["aposentadorias"]
)

df_relacoes_previdenciarias[
    [
        "ano",
        "contribuintes_por_beneficio",
        "contribuintes_por_aposentadoria"
    ]
].round(2)

     ano  contribuintes_por_beneficio  contribuintes_por_aposentadoria
0   2005                         1.36                             2.49
1   2006                         1.36                             2.48
2   2007                         1.45                             2.62
3   2008                         1.52                             2.74
4   2009                         1.52                             2.72
5   2010                         1.58                             2.85
6   2011                         1.64                             2.96
7   2012                         1.69                             3.04
8   2013                         1.69                             3.04
9   2014                         1.69                             3.02
10  2015                         1.64                             2.91
11  2016                         1.54                             2.72
12  2017                         1.48                             2.58
13  2018                         1.47                             2.53
14  2019                         1.49                             2.51
15  2020                         1.43                             2.41
16  2021                         1.52                             2.55
17  2022                         1.55                             2.62
18  2023                         1.54                             2.65

## Relação entre população em idade potencialmente ativa e população idosa

Para acompanhar a transformação da estrutura etária brasileira no período histórico, foi calculada a relação entre a população de 15 a 64 anos e a população com 60 anos ou mais.

O indicador representa uma relação demográfica e não corresponde à quantidade de contribuintes por aposentado ou beneficiário da Previdência Social.

In [20]:
df_relacao_demografica = df_historico_gold[
    [
        "ano",
        "populacao_15_64",
        "populacao_60_mais"
    ]
].copy()

df_relacao_demografica["pessoas_15_64_por_idoso"] = (
    df_relacao_demografica["populacao_15_64"]
    / df_relacao_demografica["populacao_60_mais"]
)

df_relacao_demografica[
    [
        "ano",
        "pessoas_15_64_por_idoso"
    ]
].round(2)

     ano  pessoas_15_64_por_idoso
0   2005                     7.01
1   2006                     6.90
2   2007                     6.79
3   2008                     6.66
4   2009                     6.54
5   2010                     6.39
6   2011                     6.24
7   2012                     6.08
8   2013                     5.93
9   2014                     5.77
10  2015                     5.61
11  2016                     5.45
12  2017                     5.29
13  2018                     5.13
14  2019                     4.97
15  2020                     4.83
16  2021                     4.71
17  2022                     4.58
18  2023                     4.44

## Consolidação dos indicadores históricos

Os indicadores demográfico e previdenciários são reunidos a seguir para permitir a comparação de suas trajetórias entre 2005 e 2023.

A análise conjunta permite observar se as mudanças na relação entre contribuintes e benefícios acompanharam ou não a transformação da estrutura etária da população brasileira.

In [21]:
df_indicadores_historicos = (
    df_relacao_demografica[
        ["ano", "pessoas_15_64_por_idoso"]
    ]
    .merge(
        df_relacoes_previdenciarias[
            [
                "ano",
                "contribuintes_por_beneficio",
                "contribuintes_por_aposentadoria"
            ]
        ],
        on="ano",
        how="inner",
        validate="one_to_one"
    )
)

df_indicadores_historicos.round(2)

,ano,pessoas_15_64_por_idoso,contribuintes_por_beneficio,contribuintes_por_aposentadoria
0,2005,7.01,1.36,2.49
1,2006,6.90,1.36,2.48
2,2007,6.79,1.45,2.62
3,2008,6.66,1.52,2.74
4,2009,6.54,1.52,2.72
5,2010,6.39,1.58,2.85
6,2011,6.24,1.64,2.96
7,2012,6.08,1.69,3.04
8,2013,5.93,1.69,3.04
9,2014,5.77,1.69,3.02
10,2015,5.61,1.64,2.91
11,2016,5.45,1.54,2.72
12,2017,5.29,1.48,2.58
13,2018,5.13,1.47,2.53
14,2019,4.97,1.49,2.51
15,2020,4.83,1.43,2.41
16,2021,4.71,1.52,2.55
17,2022,4.58,1.55,2.62
18,2023,4.44,1.54,2.65

In [22]:
anos_destaque = [2005, 2012, 2014, 2020, 2023]

df_indicadores_historicos[
    df_indicadores_historicos["ano"].isin(anos_destaque)
].round(2)

,ano,pessoas_15_64_por_idoso,contribuintes_por_beneficio,contribuintes_por_aposentadoria
0,2005,7.01,1.36,2.49
7,2012,6.08,1.69,3.04
9,2014,5.77,1.69,3.02
15,2020,4.83,1.43,2.41
18,2023,4.44,1.54,2.65

### Verificação dos fatores demográficos

Para complementar a análise da estrutura etária, são observadas algumas variáveis demográficas associadas ao processo de envelhecimento populacional no período histórico.

Nesta etapa são consideradas a taxa de fecundidade, a expectativa de vida e a idade mediana da população.

In [23]:
df_fatores_demograficos = df_demografia_brasil[
    (df_demografia_brasil["ano"] >= 2005) &
    (df_demografia_brasil["ano"] <= 2023)
][
    [
        "ano",
        "taxa_fecundidade",
        "expectativa_vida",
        "idade_mediana"
    ]
].copy()

df_fatores_demograficos.round(2)

     ano  taxa_fecundidade  expectativa_vida  idade_mediana
5   2005              1.95             73.02          27.04
6   2006              1.88             73.49          27.44
7   2007              1.82             73.73          27.86
8   2008              1.82             73.96          28.29
9   2009              1.77             74.14          28.72
10  2010              1.75             74.36          29.18
11  2011              1.77             74.54          29.64
12  2012              1.76             74.76          30.09
13  2013              1.75             75.00          30.53
14  2014              1.79             75.20          30.97
15  2015              1.82             75.35          31.40
16  2016              1.72             75.55          31.84
17  2017              1.76             75.72          32.29
18  2018              1.78             75.99          32.73
19  2019              1.73             76.22          33.16
20  2020              1.66             74.81          33.57
21  2021              1.64             72.78          33.96
22  2022              1.58             75.45          34.36
23  2023              1.57             76.39          34.81

### Síntese da análise histórica — 2005 a 2023

Entre 2005 e 2023, a estrutura etária da população brasileira apresentou uma transformação contínua. A relação entre a população de 15 a 64 anos e a população com 60 anos ou mais caiu de 7,01 para 4,44, enquanto a população idosa cresceu em ritmo superior ao da população em idade potencialmente ativa.

No mesmo período, os indicadores previdenciários não apresentaram uma trajetória linear. Entre 2005 e 2012/2014, houve forte expansão da base de contribuintes, permitindo melhora das relações entre contribuintes, benefícios e aposentadorias, mesmo diante do avanço do envelhecimento populacional. A partir de 2015, a redução e posterior recuperação da base contributiva produziram mudanças nessas relações, mostrando a influência das condições econômicas e do mercado de trabalho sobre os indicadores previdenciários.

A análise demográfica também mostrou redução da taxa de fecundidade, aumento da idade mediana e crescimento da expectativa de vida no período, embora esta última tenha apresentado queda temporária durante os anos da pandemia.

Os resultados indicam, portanto, que a transformação demográfica apresenta uma tendência contínua, enquanto os indicadores previdenciários também respondem a fatores econômicos, trabalhistas e institucionais. Dessa forma, a relação entre envelhecimento populacional e Previdência Social não deve ser interpretada de maneira isolada ou exclusivamente causal.

## Análise das projeções demográficas — 2023 a 2070

Esta etapa analisa exclusivamente as projeções demográficas para o Brasil, com o objetivo de identificar como a relação entre a população em idade potencialmente ativa e a população idosa poderá se modificar nas próximas décadas.

As projeções não são utilizadas para estimar o número futuro de contribuintes, benefícios, aposentadorias ou resultados financeiros da Previdência Social.

In [24]:
df_projecao_demografica = df_demografia_brasil[
    (df_demografia_brasil["ano"] >= 2023) &
    (df_demografia_brasil["ano"] <= 2070)
][
    [
        "ano",
        "populacao_total",
        "populacao_15_64",
        "populacao_60_mais",
        "taxa_fecundidade",
        "expectativa_vida",
        "idade_mediana",
        "indice_envelhecimento"
    ]
].copy()

df_projecao_demografica["pessoas_15_64_por_idoso"] = (
    df_projecao_demografica["populacao_15_64"] /
    df_projecao_demografica["populacao_60_mais"]
)

df_projecao_demografica.round(2)

,ano,populacao_total,populacao_15_64,populacao_60_mais,taxa_fecundidade,expectativa_vida,idade_mediana,indice_envelhecimento,pessoas_15_64_por_idoso
23,2023,211695158,146375852,32981491,1.57,76.39,34.81,77.56,4.44
24,2024,212583750,146815459,34169617,1.55,76.61,35.25,81.25,4.30
25,2025,213421037,147170695,35370902,1.53,76.82,35.69,85.06,4.16
26,2026,214211951,147504526,36570129,1.51,77.03,36.13,89.06,4.03
27,2027,214959713,147827324,37756883,1.50,77.23,36.56,93.26,3.92
28,2028,215667282,148119414,38928026,1.49,77.44,36.99,97.60,3.80
29,2029,216337693,148417733,40088628,1.48,77.64,37.43,102.19,3.70
30,2030,216973093,148758847,41243737,1.47,77.84,37.85,107.17,3.61
31,2031,217562970,149021283,42397965,1.46,78.04,38.28,112.22,3.51
32,2032,218096284,149203771,43555940,1.46,78.23,38.71,117.35,3.43
33,2033,218574144,149413458,44713297,1.45,78.42,39.13,122.89,3.34
34,2034,218997707,149571434,45872706,1.45,78.61,39.55,128.61,3.26
35,2035,219367247,149594746,47051618,1.45,78.80,39.97,134.28,3.18
36,2036,219681891,149495429,48270206,1.45,78.99,40.39,139.98,3.10
37,2037,219940741,149271248,49540659,1.44,79.17,40.81,145.72,3.01
38,2038,220144140,148948749,50866243,1.44,79.35,41.22,151.57,2.93
39,2039,220292836,148550344,52236970,1.44,79.53,41.63,157.60,2.84
40,2040,220386440,148048781,53633215,1.44,79.70,42.04,163.71,2.76
41,2041,220425299,147431686,55026158,1.44,79.87,42.44,169.81,2.68
42,2042,220410205,146692237,56392977,1.44,80.04,42.84,175.86,2.60
43,2043,220341694,145830811,57728377,1.44,80.21,43.23,181.83,2.53
44,2044,220220282,144860448,59031923,1.44,80.38,43.61,187.74,2.45
45,2045,220045691,143802877,60290459,1.44,80.54,43.98,193.57,2.39
46,2046,219817347,142687553,61488537,1.44,80.70,44.34,199.25,2.32
47,2047,219535230,141538223,62615945,1.45,80.86,44.69,204.78,2.26
48,2048,219199916,140361911,63664610,1.45,81.02,45.03,210.12,2.20
49,2049,218811421,139161280,64637653,1.45,81.17,45.36,215.30,2.15
50,2050,218369418,137950440,65549776,1.45,81.32,45.69,220.39,2.10
51,2051,217873978,136744894,66422062,1.45,81.47,46.01,225.44,2.06
52,2052,217325473,135554533,67269889,1.45,81.62,46.32,230.53,2.02
53,2053,216724289,134388530,68095122,1.46,81.76,46.63,235.66,1.97
54,2054,216070026,133245397,68892807,1.46,81.91,46.92,240.85,1.93
55,2055,215362623,132111528,69662989,1.46,82.05,47.20,246.09,1.90
56,2056,214603069,130966514,70403991,1.46,82.19,47.49,251.39,1.86
57,2057,213793298,129795745,71113256,1.46,82.32,47.76,256.71,1.83
58,2058,212934075,128598484,71792720,1.47,82.46,48.03,262.08,1.79
59,2059,212025649,127380577,72439658,1.47,82.59,48.30,267.50,1.76
60,2060,211069036,126142315,73032189,1.47,82.72,48.57,272.87,1.73
61,2061,210066029,124885198,73541875,1.47,82.85,48.83,278.06,1.70
62,2062,209018787,123612099,73971580,1.48,82.97,49.10,283.07,1.67
63,2063,207928784,122321645,74330256,1.48,83.10,49.37,287.89,1.65
64,2064,206797115,121016520,74629781,1.48,83.22,49.64,292.56,1.62
65,2065,205625259,119717570,74878965,1.48,83.34,49.92,297.09,1.60
66,2066,204415091,118452256,75087501,1.49,83.46,50.18,301.48,1.58
67,2067,203168549,117217993,75204572,1.49,83.57,50.43,305.50,1.56
68,2068,201887385,116005914,75277542,1.49,83.69,50.68,309.32,1.54
69,2069,200573375,114803980,75315921,1.49,83.80,50.93,312.95,1.52
70,2070,199228708,113603532,75292150,1.50,83.91,51.17,316.24,1.51

In [25]:
anos_destaque_projecao = [2023, 2030, 2040, 2050, 2060, 2070]

df_pontos_projecao = df_projecao_demografica[
    df_projecao_demografica["ano"].isin(anos_destaque_projecao)
][
    [
        "ano",
        "populacao_total",
        "populacao_15_64",
        "populacao_60_mais",
        "taxa_fecundidade",
        "expectativa_vida",
        "idade_mediana",
        "indice_envelhecimento",
        "pessoas_15_64_por_idoso"
    ]
].copy()

df_pontos_projecao.round(2)

,ano,populacao_total,populacao_15_64,populacao_60_mais,taxa_fecundidade,expectativa_vida,idade_mediana,indice_envelhecimento,pessoas_15_64_por_idoso
23,2023,211695158,146375852,32981491,1.57,76.39,34.81,77.56,4.44
30,2030,216973093,148758847,41243737,1.47,77.84,37.85,107.17,3.61
40,2040,220386440,148048781,53633215,1.44,79.70,42.04,163.71,2.76
50,2050,218369418,137950440,65549776,1.45,81.32,45.69,220.39,2.10
60,2060,211069036,126142315,73032189,1.47,82.72,48.57,272.87,1.73
70,2070,199228708,113603532,75292150,1.50,83.91,51.17,316.24,1.51

In [26]:
inicio = df_projecao_demografica[
    df_projecao_demografica["ano"] == 2023
].iloc[0]

fim = df_projecao_demografica[
    df_projecao_demografica["ano"] == 2070
].iloc[0]

variacoes_2023_2070 = {
    "populacao_total": ((fim["populacao_total"] / inicio["populacao_total"]) - 1) * 100,
    "populacao_15_64": ((fim["populacao_15_64"] / inicio["populacao_15_64"]) - 1) * 100,
    "populacao_60_mais": ((fim["populacao_60_mais"] / inicio["populacao_60_mais"]) - 1) * 100,
    "pessoas_15_64_por_idoso": (
        (fim["pessoas_15_64_por_idoso"] / inicio["pessoas_15_64_por_idoso"]) - 1
    ) * 100
}

pd.Series(variacoes_2023_2070).round(2)

populacao_total             -5.89
populacao_15_64            -22.39
populacao_60_mais          128.29
pessoas_15_64_por_idoso    -66.00
dtype: float64

In [29]:
pasta_gold.mkdir(parents=True, exist_ok=True)

# 1. Base demográfica completa
df_demografia_brasil.to_csv(
    pasta_gold / "gold_demografia.csv",
    index=False
)

# 2. Base histórica integrada
df_historico_gold.to_csv(
    pasta_gold / "gold_historico_previdencia.csv",
    index=False
)

# 3. Base das projeções demográficas
df_projecao_demografica.to_csv(
    pasta_gold / "gold_projecao_demografica.csv",
    index=False
)

print("Bases Gold exportadas com sucesso.")

Bases Gold exportadas com sucesso.

## Validação final das bases Gold

In [30]:
# Leitura das bases Gold exportadas
gold_demografia = pd.read_csv(
    pasta_gold / "gold_demografia.csv"
)

gold_historico = pd.read_csv(
    pasta_gold / "gold_historico_previdencia.csv"
)

gold_projecao = pd.read_csv(
    pasta_gold / "gold_projecao_demografica.csv"
)

# Validação final
bases_gold = {
    "gold_demografia": gold_demografia,
    "gold_historico_previdencia": gold_historico,
    "gold_projecao_demografica": gold_projecao
}

for nome, base in bases_gold.items():
    print(f"\n{nome}")
    print(f"Dimensão: {base.shape}")
    print(f"Período: {base['ano'].min()} a {base['ano'].max()}")
    print(f"Duplicidades em ano: {base['ano'].duplicated().sum()}")
    print(f"Valores ausentes: {base.isna().sum().sum()}")

gold_demografia
Dimensão: (71, 25)
Período: 2000 a 2070
Duplicidades em ano: 0
Valores ausentes: 1

gold_historico_previdencia
Dimensão: (19, 7)
Período: 2005 a 2023
Duplicidades em ano: 0
Valores ausentes: 0

gold_projecao_demografica
Dimensão: (48, 9)
Período: 2023 a 2070
Duplicidades em ano: 0
Valores ausentes: 0

In [31]:
gold_demografia[
    gold_demografia.isna().any(axis=1)
]

,ano,codigo,sigla,local,populacao_total,populacao_0_14,populacao_15_64,populacao_60_mais,populacao_65_mais,populacao_80_mais,...,taxa_crescimento,expectativa_vida,expectativa_vida_60,taxa_fecundidade,razao_dependencia_jovens,razao_dependencia_idosos,razao_dependencia_total,indice_envelhecimento,idade_media,idade_mediana
0,2000,0,BR,Brasil,174695935,52259915,111908697,15229921,10527323,2032255,...,NaN,71.102185,20.109002,2.315552,48.747147,14.206208,62.953355,29.142644,28.314517,25.286941